### ISSUE TITLE
hamster-bridge does nothing after start

### ISSUE THREAD

**Issue by Sqozz** [kraiz/hamster-bridge#13]
Hi all!
hamster-bridge seems like the perfekt tool i'm looking for. Unfortunately it does nothing after i start it.
Here is a log after starting hamster-bridge:
```
2015-02-26 12:03:18,375    INFO: Starting hamster bridge
2015-02-26 12:03:18,408    INFO: Activating listener: jira
2015-02-26 12:03:18,408    INFO: Registering <hamster_bridge.listeners.jira.JiraHamsterListener object at 0x7f8e5c141310>
2015-02-26 12:03:18,417    INFO: Starting new HTTPS connection (1): jira.domain.tld
```

I don't exactly know, how the bridge works but i whould except that hamster-bridge starts hamster after it gathered all informations from jira. For the sake of accuracy i also tried to start hamster first and then hamster-bridge and also the other way around - nothing.

Here is my (anonymized) hamster-bridge config:
```
[jira]
server_url = https://jira.domain.tld
username = foo
password = bar
auto_start = y
```

**Comment by Sqozz** [comment]
Seems, that the connection to jira works. It'd be nice, if the behavior of hamster-bridge is described somehow in the README or another document

**Comment by kraiz** [comment]
Yeah, i should add an explicit note about the supposed workflow in the readme.

You need to start hamster on your own. As soon as the stop a task, the bridge will search the title for a jira ticket, if nothing found the tags, too. When it finds one, it will log the spent time to this ticket.

There's a feature request in #11 for writing the task description to the worklog comment. This will come in to next version soon.

**Comment by kraiz** [comment]
I added some words in the README. Don't know if it's enough? What do you think?

**Comment by Sqozz** [comment]
Since i now found out how it works, your description seems pretty reasonable :)
Maybe you could add some words about the issue-finding from the hamster-bridge. My understanding is, that hamster-bridge tries to match the name (and? or? tags) to the first jira/redmine-issue it finds. What happens, if there is a matching tag and a matching name? Does hamster-bridge fillout multiple matching issues (e.g. hamstername is "issue1" and tag is "bugfix" - will hamster-bridge fillout the jira/redmine-issue "issue1 - fix something" or will it fill "issue 1337 - bugfix for xyz"?).

Since hamster-bridge does some automagic in the background, the user should know how that magic works to guarantee a stable and reasonable workflow.

BTW: used hamster-bridge today the whole time and it does it's job pretty well. So thanks for your efford in such a little but great tool :+1:

**Comment by daroczig** [comment]
Yeah, for the first time, I was similarly not sure how and when `hamster-bridge` connects to JIRA, but after using it for a while, I figured out from the logs that it's connecting to JIRA when I stop the timer. Now the README is pretty clear and helpful.

I'd add an extra note, that you have to stop the timer if you want to log something, as if you do not click on "stop the timer" and simply change to a new task, then the time is not logged. At least here :)

But it's a really minor issue, `hamster-bridge` rocks.

**Comment by kraiz** [comment]
Glad to here your happy with it.

I added some more on the issue finding. Should be fine now.
