### ISSUE TITLE
Frequent log outs from JIRA

### ISSUE THREAD

**Issue by daroczig** [kraiz/hamster-bridge#16]
Not sure if this is closely related to `hamster-bridge` or not, and I can live with it, but I thought it might be an annpoying problem for others as well, so raising this ticket. In short: my browser seems to be logged out of JIRA from time to time, despite the fact that the "remember me" feature to store the cookies is on.

After some [desktop research](https://confluence.atlassian.com/display/CLOUDKB/Getting+randomly+logged+out+of+Atlassian+Cloud), I suspect that it might be due to `hamster-jira` logging in to submit work hours. I tend to push around 10-20 worklogs a day.

Not sure if it might be improved like logging in when `hamster-jira` starts and reusing the session -- or the described symptoms are totally unrelated. Thanks for reading!

**Comment by kraiz** [comment]
`hamster-bridge` creates a connection, login with your credentials and then hold this "session" all the time. As of #10 `hamster-bridge` uses the official [jira python binding](https://pypi.python.org/pypi/jira/) for the connection. When there really are those login/logout session problems it may lie in the library. 

You can maybe check this with `hamster-bridge` turned off and a python shell within the `hamster-bridge`-virtualenv (or some other environment with `jira` installed). Run the commands from [this comment][https://github.com/kraiz/hamster-bridge/issues/10#issuecomment-75124269], then wait 10 or 20minutes and rerun the `add_worklog`-method again. Then check your login status in the browser. 

This is the exact way `hamster-bridge` is using the binding. It will hold the "JIRA"-instance all the time.

**Comment by daroczig** [comment]
Thank you very much @kraiz.
The issue seems to be resolved by upgrading `jira` to `0.41` from `0.41`.

**Comment by kraiz** [comment]
Good to know.

**Comment by daroczig** [comment]
Well, it turned out that I'm still having some issues with this, so opened https://github.com/pycontribs/jira/issues/47 -- I hope I will be able to debug this with some help. We'll see, and I will report back here if I find something useful.

**Comment by daroczig** [comment]
@kraiz can you please have a look at the related `jira` issue? @GaretJax was really kind to share his related experiences.
