### ISSUE TITLE
complains about missing dependency redmine, even though I dont want it

### ISSUE THREAD

**Issue by gregswift** [kraiz/hamster-bridge#18]
I followed the instructions for JIRA and ended up with this error:

```
$ hamster-bridge jira
Traceback (most recent call last):
  File "/usr/bin/hamster-bridge", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/hamster_bridge/__init__.py", line 24, in main
    (lc.short_name, lc) for lc in [import_listener(l) for l in LISTENERS]
  File "/usr/lib/python2.7/site-packages/hamster_bridge/__init__.py", line 9, in import_listener
    mod = __import__(name.rsplit('.', 1)[0])
  File "/usr/lib/python2.7/site-packages/hamster_bridge/listeners/redmine.py", line 8, in <module>
    from redmine import Redmine
ImportError: No module named redmine
```

Obviously I can jsut install that module... but since I'm not trying to use redmine thats a little annoying.

**Comment by Fank** [comment]
Yea you need to install the redmine adapter too. Also if you dont need it.

**Comment by gregswift** [comment]
right... but the documentation doesn't reflect that, and should probably be adjusted overall to just install it.  Either that or actually make it a soft dependency

**Comment by kraiz** [comment]
That's not fine, indeed. Got that redmine-adapter via PR and never checked it as i'm not running an instance. I just moved the import statements out of the startup. Can you please give it a try by installing:

    pip install https://github.com/kraiz/hamster-bridge/zipball/redmine-import-18

**Comment by gregswift** [comment]
That fixed it.  Thanks.

Now if only i could figure out why nothing happens at all anyway :(

**Comment by kraiz** [comment]
0.5.1 is on pypi :)

**Comment by gregswift** [comment]
:+1:
