### ISSUE TITLE
Listener plugin loading

### ISSUE THREAD

**Issue by dArignac** [kraiz/hamster-bridge#5]
For now there is only the LISTENERS list within the hamster_bridge module where people are able to add new listeners.
You should somehow create a plugin mechanism to (maybe also on runtime) allow loading of additional listeners or a subset of listeners. (You already wrote that as a TODO in code, I extract it as issue so it will not get lost)

Also consider that there is currently one dependeny within the setup.py (jira-python) that only applies to the JIRA listener. If I only want to use f.e. the Redmine listener I do not want to install JIRA libs.

**Comment by kraiz** [comment]
Sure this would be great, i thought this in the beginning and left this comment. But as this tool is this tiny, there are no feature requests for further trackers and i'm very open for PRs, i close this.
